# Model DD-selfcal pipeline configuration file

selfcal_cycles:
  # Cycle 1
  - tesselation:
      num_patches: 10

    ddecal:
      solve_mode: scalarphase
      solve_solint: 30
      solve_nchan: 1
      override_dp3_options: {}

    imaging:
      override_wsclean_options:
        "-mgain": 0.7

  # Cycle 2
  - tesselation:
      num_patches: 10

    ddecal:
      solve_mode: scalarphase
      solve_solint: 30
      solve_nchan: 1
      override_dp3_options: {}

    imaging:
      override_wsclean_options: {}

  # Cycle 3
  - tesselation:
      num_patches: 10

    ddecal:
      solve_mode: complexgain
      solve_solint: 30
      solve_nchan: 1
      override_dp3_options: {}

    imaging:
      override_wsclean_options: {}
